Algoritmo "media_alunos"

Var
n1,n2,n3,n4,med:real


Inicio
escreval ("informe a nota 1")
leia (n1)
escreval ("informe a nota 2")
leia (n2)
escreval ("informe a nota 3")
leia (n3)
escreval ("informe a nota 4")
leia (n4)

med:=(n1+n2+n3+n4)/4
escreval ("a media final do aluno é", med)

se (med<5) entao
    escreval escreval ("aluno reprovado")
fimse

se (med>5) entao
    escreval ("aluno aprovado")
fimse


Fimalgoritmo
